global using NoteSystemDao.DbItems;
global using System.Data;
global using System.Linq;
global using Xunit;
global using MySql.Data.MySqlClient;
global using NoteSystemDao;
global using System.Reflection;
global using NoteSystemDao.Orm;
global using NoteSystemDao.Orm.MyAttributes;